version: '3'

services:
  web:
    container_name: cer2_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - cer2_network

  db:
    container_name: cer2_db
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cer2
      POSTGRES_PASSWORD: holaquehace1
    networks:
      - cer2_network

networks:
  cer2_network:
    driver: bridge
